### PR TITLE
api: use pointer to `const`

### PR DESCRIPTION
**Pull request by vil02**
### Description

Pointers to consts could be use in these places.

### Checklist

- [x] A description of the changes in this PR is mentioned above.
- [x] All the new and existing tests pass.
- [x] The code follows the code style and conventions of the project.
- [x] No plagiarized, duplicated, or repetitive code that has been directly copied from another source.
- [x] I have read the whole [Contributing guidelines](https://jule.dev/contribute) of the project and its resources/related pages.

### Note to reviewers

Use pointer to `const`.

### CODE REVIEW

**Review by mertcandav — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by mertcandav** [comment]
I'll revert PR because of compilation problems.

**Comment by vil02** [comment]
> I'll revert PR because of compilation problems.

Sorry for the problems. Do you have some idea how to improve the CI to avoid such situations in the future?

**Comment by mertcandav** [comment]
Current CI processes may need some modification, I'll take a look at that.
I think I can reach to the necessary CI responsiveness.

**Comment by mertcandav** [comment]
I opened an issue about this.

- #100

**Pull request merged**
