### PR TITLE
api: use fixed width integer types to define jule types

### PR DESCRIPTION
**Pull request by vil02**
### Description

Since the true size of _basic_ integer types might be _everything_ depended, I suggest to define jule integer types using the [_fixed with integer types_](https://en.cppreference.com/w/cpp/types/integer).

### Checklist

- [x] A description of the changes in this PR is mentioned above.
- [x] All the new and existing tests pass.
- [x] The code follows the code style and conventions of the project.
- [x] No plagiarized, duplicated, or repetitive code that has been directly copied from another source.
- [x] I have read the whole [Contributing guidelines](https://jule.dev/contribute) of the project and its resources/related pages.

### Note to reviewers

Use fixed width integer types to define jule types.

### CODE REVIEW

**Review by mertcandav — APPROVED** [review]
LGTM. Thanks for your contribution.

**Comment by vil02** [comment]
@mertcandav do you know what have happened in [this job](https://github.com/julelang/jule/actions/runs/7747594163/job/21128422506)?

**Comment by mertcandav** [comment]
Not yet. I will review this problem as far as soon. I will revert this PR and open an issue for that.
If you have idea about that, please share with us via relevant issue.

Thanks.

**Comment by vil02** [comment]
(since the issue is not yet there)

Did you try to simply rerun the failed jobs? When I synchronized my fork, both [build](https://github.com/vil02/jule/actions/runs/7748029567) and [tests](https://github.com/vil02/jule/actions/runs/7748029563) were successful.

**Comment by mertcandav** [comment]
No, I'll investigate. There are might be more deep problems.
But issue also discuss some things. Then, I think we can merge this PR.

**Pull request merged**
