### PR TITLE
ci: merge the GitHub Actions workflows

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Merge the GitHub Actions workflows. This will:
  - Make things cleaner.
  - Run for all OSes on the same workflow.
  - Seamlessly check all jobs in one place ([**example**](https://github.com/Panquesito7/jule/actions/runs/3535265002)).
  - Run directly on all pull requests and multiple branches.

### CODE REVIEW

**Comment by mertcandav** [comment]
Hi,
Looks good but can you separate linux and darwin?
Because of we can have multiple linux or darwin action in the future.
We think it would be better for us to see actions as a separately by kernels.

**Comment by Panquesito7** [comment]
> ...can you separate Linux and Darwin?

So only separate Linux and Darwin to multiple jobs, and keep all the other stuff as-is?
I like to have everything in one file to make everything cleaner, and you can still check each job (like seen [**here**](https://github.com/Panquesito7/jule/actions/runs/3535265002)). But if you prefer to have it separated into multiple actions, then we can close this PR. 🙂

**Comment by mertcandav** [comment]
We like your single file approach. What we are wondering is, can we keep all kernels separate in this single file?
For example, windows is alone but linux and darwin are a matrix. We want to get rid of this matrix.

**Comment by Panquesito7** [comment]
> For example, windows is alone but linux and darwin are a matrix. We want to get rid of this matrix.

Oh, like having separate jobs for Linux and Darwin?

**Comment by mertcandav** [comment]
Yes, something like that.

**Comment by mertcandav** [comment]
LGTM, thanks for your contribution.

**Pull request merged**
